#ifndef TYPESINTERFACELOGICIELLE_H
#define TYPESINTERFACELOGICIELLE_H

#define CAPTEURS_ID           (unsigned long) 0x290
#define ENTREESTOR_COFFRET_ID (unsigned long) 0x190
#define SORTIESTOR_COFFRET_ID (unsigned long) 0x210
#define ENTREESTOR_SOMMET_ID  (unsigned long) 0x200
#define SORTIESTOR_SOMMET_ID  (unsigned long) 0x220

// #### NOEUD COFFRET PECHEUR ####

// Module entrées analogiques
#define SIGNAL_CANAL
#define SIGNAL_RIVIERE

// 1er module entrées TOR
#define DETECT_HAUT_GRILLE 0x80
#define DETECT_BAS_GRILLE
#define DETECT_HAUT_VANNE
#define DETECT_BAS_VANNE
#define NIVEAU_BAS_POIRE
#define DEFAUT_MOU_DE_CABLE
#define DETECTEUR_SURCHARGE

// 2eme module entrées TOR
#define PREMIERE_CAME_SELECTEUR_CADENCE
#define DEUXIEME_CAME_SELECTEUR_CADENCE
#define TROISIEME_CAME_SELECTEUR_CADENCE
#define CUVE_DETECTEUR_HAUT
#define CUVE_DETECTEUR_HAUT_GVPV
#define CUVE_DETECTEUR_BAS_GVPV
#define CUVE_DETECTEUR_TRES_BAS

// 3eme module entrées TOR
#define CONFIRMATION_MARCHE_POMPE
#define CONFIRMATION_MONTEE_CUVE
#define CONFIRMATION_DESCENTE_CUVE
#define CONFIRMATION_PETITE_VITESSE
#define CONFIRMATION_GRANDE_VITESSE
#define CONFIRMATION_CENTRALE

// 1er module sorties TOR
#define MONTEE_GRILLE
#define DESCENTE_GRILLE
#define MONTEE_VANNE
#define DESCENTE_VANNE
#define CHAUFFAGE_HUILE // vanne_by-pass
#define DEMARRAGE_POMPE

// 2eme module sorties TOR
#define MONTEE_CUVE
#define DESCENTE_CUVE
#define PETITE_VITESSE
#define GRANDE_VITESSE
#define MARCHE_CENTRALE_HYDRAULIQUE

// #### NOEUD SOMMET PECHEUR ####

// 1er module entrées TOR
#define BP_ARRET_URGENCE
#define BP_MONTEE_PV
#define BP_MONTEE_GV
#define BP_DESCENTE_PV
#define BP_DESCENTE_GV
#define BP_MARCHE_CENTRALE_HYDRAULIQUE
#define BP_ARRET_CENTRALE_HYDRAULIQUE

// 2eme module entrées TOR
#define MARCHE_MANUELLE
#define MARCHE_AUTOMATIQUE
#define BP_MONTEE_GRILLE
#define BP_DESCENTE_GRILLE
#define BP_MONTEE_VANNE
#define BP_DESCENTE_VANNE
#define BP_MARCHE_POMPE
#define BP_ARRET_POMPE

// 3eme module entrées TOR
#define BP_CYCLE_PECHEUR
#define BP_LANCEMENT_CYCLE_ARMOIRE
#define ACQUITTEMENT_DEFAUT
#define THERMOSTAT_HUILE
#define NIVEAU_BAS_HUILE

// Module sorties TOR
#define VOYANT_DEFAUT_TEMPERATURE
#define VOYANT_NIVEAU_BAS_POIRE
#define VOYANT_DEFAUT_CYCLE
#define VOYANT_DEFAUT_TREUIL
#define VOYANT_DEFAUT_CENTRALE_HYDRAULIQUE
#define VOYANT_DEFAUT_POMPE
#define COMPTEUR_CYCLE
#define DEFAUT_GENERAL

#endif // TYPESINTEMRFACELOGICIELLE_H
